CarBook-master/Frontends/UdemyCarBook.WebUI/Controllers/ContactController.cs
using CarBook.Dto.ContactDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace UdemyCarBook.WebUI.Controllers
{
    public class ContactController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public ContactController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(CreateContactDto createContactDto)
        {
            createContactDto.SendDate = DateTime.Parse(DateTime.Now.ToShortDateString());

            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createContactDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7094/api/Contacts/CreateContact", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

CarBook-master/Frontends/UdemyCarBook.WebUI/Views/Contact/Index.cshtml
@model CreateContactDto
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/UILayout/Index.cshtml";
}

<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex mb-5 contact-info">

            <!-- ======= _FooterAddressPartial Section ======= -->
            @await Component.InvokeAsync("_FooterAddressPartialVC")
            <!-- End _FooterAddressPartial Section -->

            @* <!-- ======= _MessageBox Section ======= -->
            @await Component.InvokeAsync("_MessageBoxPartialVC")
            <!-- End _MessageBox Section --> *@

            <div class="col-md-8 block-9 mb-md-5">
                <form method="post" asp-controller="Contact" asp-action="Index" class="bg-light p-5 contact-form">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Name" asp-for="Name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Email" asp-for="Email">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Subject" asp-for="Subject">
                    </div>
                    <div class="form-group">
                        <textarea id="" cols="30" rows="7" class="form-control" placeholder="Message" asp-for="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                    </div>
                </form>

            </div>
            
        </div>

        <!-- ======= _Map Section ======= -->
        @await Component.InvokeAsync("_MapPartialVC")
        <!-- End _Map Section -->
    </div>
</section>