CarBook-master/Frontends/UdemyCarBook.WebUI/Controllers/AdminBrandController.cs
using CarBook.Dto.BrandDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace CarBook.WebUI.Controllers
{
    public class AdminBrandController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AdminBrandController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7094/api/Brands/BrandList");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ListBrandDto>>(jsonData);


                return View(values);
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateBrand()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBrand(CreateBrandDto createBrandDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createBrandDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7094/api/Brands/CreateBrand", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> RemoveBrand(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:7094/api/Brands/RemoveBrand/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateBrand(int id)
        {

            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7094/api/Brands/GetBrand/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var value = JsonConvert.DeserializeObject<UpdateBrandDto>(jsonData);

                return View(value);
            }

            return View();
        }

        [HttpPost]

        public async Task<IActionResult> UpdateBrand(UpdateBrandDto updateBrandDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateBrandDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("https://localhost:7094/api/Brands/UpdateBrand", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();

        }
    }
}

CarBook-master/Frontends/UdemyCarBook.WebUI/Controllers/AdminDashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarBook.WebUI.Controllers
{
    public class AdminDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CarBook-master/Frontends/UdemyCarBook.WebUI/Views/AdminBrand/CreateBrand.cshtml
@model CreateBrandDto
@{
    ViewData["Title"] = "CreateBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Brands</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="AdminDashboard" asp-action="Index">Dashboard</a></li>
                    <li class="breadcrumb-item"><a asp-controller="AdminBrand" asp-action="Index">Brand</a></li>
                    <li class="breadcrumb-item">Add Brand</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class="card">
    <div class="card-body">

        <h4 class="card-title">Create Brand</h4>
        <p class="card-subtitle mb-4">You can create brand on table below.</p>

        <form method="post">
            <div class="form-group">
                <label for="exampleInputModel">Brand</label>
                <input type="text" class="form-control" id="exampleInputFeatureName" asp-for="Name" placeholder="Enter Brand">
            </div>
            <button type="submit" class="btn btn-primary waves-effect waves-light" asp-controller="AdminBrand" asp-action="CreateBrand">Add Brand</button>
        </form>

    </div> <!-- end card-body-->
</div> <!-- end card-->

CarBook-master/Frontends/UdemyCarBook.WebUI/Views/AdminBrand/Index.cshtml
@model List<ListBrandDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    int count = 0;
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Brands</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="AdminDashboard" asp-action="Index">Dashboard</a></li>
                    <li class="breadcrumb-item active">Brand</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Brands Table</h4>
                <p class="card-subtitle mb-4">
                    You can do CRUD operations on that table.
                </p>
                <div class="table-responsive">
                    @if (Model.Count < 1)
                    {
                        <p><b>There is no Brand yet.Please start creating one.</b></p>
                    }
                    else
                    {
                        <table class="table mb-0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Brand</th>
                                    <th>Delete</th>
                                    <th>Update</th>
                                    <th>Cars</th>


                                </tr>
                            </thead>
                            <tbody>
                                <script type="text/javascript">
                                    function confirmDelete() {
                                        return confirm("Are you sure you want to delete this feature?");
                                    }
                                </script>

                                @foreach (var item in Model)
                                {
                                    count++;
                                    <tr>
                                        <th scope="row">@count</th>
                                        <td>@item.Name</td>
                                        <td><a asp-controller="AdminBrand" asp-action="RemoveBrand" asp-route-id="@item.BrandID" class="btn btn-outline-danger" onclick="return confirmDelete();">Delete</a></td>
                                        <td><a asp-controller="AdminBrand" asp-action="UpdateBrand" asp-route-id="@item.BrandID" class="btn btn-outline-success">Update</a></td>
                                        <td><a asp-controller="AdminBrand" asp-action="UpdateBrand" asp-route-id="@item.BrandID" class="btn btn-outline-dark">Cars</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    <br />
                    <a asp-controller="AdminBrand" asp-action="CreateBrand" class="btn btn-outline-primary">Add New Brand</a>
                </div>

            </div>
            <!-- end card-body-->
        </div>
        <!-- end card -->

    </div>
    <!-- end col -->



</div>

CarBook-master/Frontends/UdemyCarBook.WebUI/Views/AdminBrand/UpdateBrand.cshtml
@model UpdateBrandDto
@{
    ViewData["Title"] = "UpdateBrand";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Brands</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="AdminDashboard" asp-action="Index">Dashboard</a></li>
                    <li class="breadcrumb-item"><a asp-controller="AdminBrand" asp-action="Index">Brand</a></li>
                    <li class="breadcrumb-item">Update Brand</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class="card">
    <div class="card-body">

        <h4 class="card-title">Update Brand</h4>
        <p class="card-subtitle mb-4">You can update brand on table below.</p>

        <form method="post">
            <input type="hidden" asp-for=BrandID />
            <div class="form-group">
                <label for="exampleInputModel">Model</label>
                <input type="text" class="form-control" id="exampleInputBrandName" asp-for="Name" placeholder="Enter Brand">
            </div>
            <button type="submit" class="btn btn-primary waves-effect waves-light" asp-controller="AdminBrand" asp-action="UpdateBrand">Update Brand</button>
        </form>

    </div> <!-- end card-body-->
</div> <!-- end card-->